### ISSUE TITLE
Non sapevo come mettermi in contatto con voi!

### ISSUE THREAD

**Issue by emaiannone** [domenico-napolitano/DiscoverEasy#1]
Riguardo alla presenza dell'entity Negoziante, sono stato un po' impreciso. I dati relativi all'**Account** devono essere considerat in un oggetti entity, perché tutti i dati dell'utente finiscono, gioco forza, in memoria (in particolare quella persistente), quindi un oggetto Account ci vuole eccome (o qualche nome simile). Scusatemi se sono stato impreciso, ma avendo visto "Utente" avevo subito pensato che avevate "convertito" tutti gli attori in quella classe, cosa che invece non va fatta!

**Comment by domenico-napolitano** [comment]
Ti ringrazio del pensiero Emanuele. Volevo chiederti se era possibile un
incontro prima di martedì.

Il mar 12 nov 2019, 16:51 Emanuele Iannone <notifications@github.com> ha
scritto:

**Comment by emaiannone** [comment]
Domani dopo le 11 sono disponibile. Non spargete la voce però!! Ci sentiamo, e vi lascio la mia mail: e.iannone16@studenti.unisa.it
Contattatemi stesso voi, altrimenti mi dimentico

**Comment by domenico-napolitano** [comment]
Certo, rimane tra noi 🤫. Fammi sapere in che luogo.
Ti ringrazio, a domani ❤

Il mar 12 nov 2019, 17:21 Emanuele Iannone <notifications@github.com> ha
scritto:

**Comment by domenico-napolitano** [comment]
Emanuele puoi farci sapere dove incontrarci?
Inoltre ti volevo chiedere se potevamo posticipare l'incontro di 30m perché
stiamo facendo lezione

Il mar 12 nov 2019, 17:29 Domenico Napolitano <
domeniconapolitano97@gmail.com> ha scritto:

**Comment by emaiannone** [comment]
Ciao,

Ho appena finito lezione, solo che ora devo passare un attimo dalla de rosa
e poi devo incontrarmi con il mio team di progetto. Mandami un messaggio
sue telegram @emarik per le 12.30.

Il mer 13 nov 2019, 10:41 domenico-napolitano <notifications@github.com> ha
scritto:
